"""Project Indexer configuration."""

EXCLUDED_DIRS = {
    "node_modules",
    ".git",
    ".svn",
    "__pycache__",
    "bin",
    "build",
    "dist",
    "out",
    "Packages",
}

EXCLUDED_EXTENSIONS = {
    ".meta",
    ".gitkeep",
    ".DS_Store",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".bmp",
    ".tga",
    ".dds",
    ".fbx",
    ".obj",
    ".blend",
    ".ma",
    ".mb",
    ".wav",
    ".mp3",
    ".ogg",
    ".flac",
    ".avi",
    ".mp4",
    ".mov",
    ".ttf",
    ".otf",
}

ROBLOX_SERVICES = {
    "Workspace": "workspace",
    "ReplicatedStorage": "replicated_storage",
    "ServerStorage": "server_storage",
    "ServerScriptService": "server_script_service",
    "StarterGui": "starter_gui",
    "StarterPlayer": "starter_player",
    "StarterPack": "starter_pack",
    "ReplicatedFirst": "replicated_first",
    "Players": "players",
    "DataStoreService": "data_store_service",
    "HttpService": "http_service",
    "MarketplaceService": "marketplace_service",
    "UserInputService": "user_input_service",
    "RunService": "run_service",
    "TweenService": "tween_service",
    "CollectionService": "collection_service",
    "PathfindingService": "pathfinding_service",
    "Lighting": "lighting",
    "Debris": "debris",
    "Teams": "teams",
    "Chat": "chat",
    "SoundService": "sound_service",
    "TeleportService": "teleport_service",
    "MessagingService": "messaging_service",
    "MemoryStoreService": "memory_store_service",
    "ContextActionService": "context_action_service",
    "TextService": "text_service",
    "InsertService": "insert_service",
    "BadgeService": "badge_service",
    "SocialService": "social_service",
    "GroupService": "group_service",
    "FriendService": "friend_service",
    "PolicyService": "policy_service",
    "ProximityPromptService": "proximity_prompt_service",
}

ROJO_SOURCE_PATHS = ["src", "lib", "source"]
